### ISSUE TITLE
alias support

### ISSUE THREAD

**Issue by latel** [ngfk/yaml-import-loader#2]
do this loader supports alias through import?

prop.yml
```yaml
---
mod:
  account: &account
      icon: all-account
      route: /account/personal
```

index.yml
```yaml
---
!import ./prop.yml
entry:
    - *account
```

this throws 
Module build failed: YAMLException: unidentified alias "account" in "index.yml" at line 8, column 16:
            - *quickTrade
