### ISSUE TITLE
Is there any alias support at all?

### ISSUE THREAD

**Issue by mdix** [ngfk/yaml-import-loader#3]
Thanks @ngfk for working at this loader. 

I tried to make this work, but I get an undefined alias error:

```yaml
STATUS:
  DRAFT: &draft 'draft'

STATUS_ICON:
  *draft: 'draft'
```

Error is
```
Module build failed (from ./node_modules/yaml-import-loader/dist/index.js):
YAMLException: unidentified alias "draft:" in "status.const.yaml" at line 9, column 10:
      *draft: 'draft'
```

Did I understand the aliases wrong? I checked with a yaml to json parser and it worked well. Thanks for your help. :-)
